
title: paulieOS
# description:  update now

email: kevin@kevaid.com
baseurl: "" 
url: ""
twitter_username: nifnut
theme: minima
plugins:
  - jekyll-feed

collections:
  windows:
    output: true
    permalink: /:path/

cachedz: 2